minerva/cursos/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views

app_name = "cursos"

urlpatterns = [
    path('', views.cursos, name="list"),
    path('nuevo/', views.curso_nuevo, name="nuevo"),
    path('<int:id>/', views.curso_detail, name="detail"),
    path('<int:id>/editar/', views.curso_editar, name="editar"),
    path('<int:id>/borrar/', views.curso_borrar, name="borrar"),
    path('<int:id>/alumnos/nuevo/', views.curso_nuevo_alumno, name="nuevo_alumno"),
    path('<int:id>/alumnos/<int:alumno_id>/editar/', views.curso_editar_alumno, name="editar_alumno"),
    path('<int:id>/alumnos/<int:alumno_id>/borrar/', views.curso_borrar_alumno, name="borrar_alumno"),
]

minerva/minerva/urls.py
from django.contrib import admin
from django.urls import path, include
from cursos import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path("cursos/", include("cursos.urls", namespace="cursos")),
]

minerva/cursos/models.py
from django.db import models


class Modalidad(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural='Modalidades'
        ordering = ("nombre", )


class Curso(models.Model):
    nombre = models.CharField(max_length=255)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    horas = models.IntegerField(default=10)
    modalidad = models.ForeignKey("Modalidad", on_delete=models.SET_NULL, null=True, blank=True)
    subvencionado = models.BooleanField(default=False)
    plazas = models.PositiveSmallIntegerField(default=25)
    horario = models.CharField(max_length=50, choices=(("m", "Mañana"), ("t", "Tarde")))

    def porcentaje_plazas(self):
        return self.alumnomatriculado_set.all().count() * 100 // self.plazas

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ("fecha_inicio", "-nombre")



class AlumnoMatriculado(models.Model):
    nombre = models.CharField(max_length=150)
    apellidos = models.CharField(max_length=150)
    fecha_matricula = models.DateTimeField(auto_now_add=True)
    curso = models.ForeignKey("Curso", on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(self.nombre, self.apellidos)

minerva/cursos/forms.py
from django import forms
from .models import *

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        exclude = []


class AlumnoForm(forms.ModelForm):
    class Meta:
        model = AlumnoMatriculado
        exclude = ["curso", ]

minerva/cursos/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import *
from .forms import *


def home(request):
    proximos = Curso.objects.all().order_by("-fecha_inicio")[:3]
    return render(request, "cursos/home.html", {
            "proximos": proximos,
        })

def cursos(request):
    qs = Curso.objects.all()
    modalidades = Modalidad.objects.all()
    modalidad_filtrada = request.GET.get("modalidad", None)

    if modalidad_filtrada:
        qs = qs.filter(modalidad__id=modalidad_filtrada)
    return render(request, "cursos/list.html", {
        "cursos": qs,
        "modalidades": modalidades,
        })


def curso_nuevo(request):
    if request.method == "POST":
        form = CursoForm(request.POST)
        if form.is_valid():
            obj = form.save()
            messages.add_message(request, messages.INFO, 'Curso creado correctamente')
            return redirect("cursos:detail", id=obj.id)
    else:
        form = CursoForm()

    return render(request, "cursos/nuevo.html", {"form": form,  "title":"Nuevo curso"})


def curso_detail(request, id):
    obj = get_object_or_404(Curso, id=id)

    return render(request, "cursos/detail.html", {
        "curso": obj,
        })

def curso_editar(request, id):
    obj = get_object_or_404(Curso, id=id)

    if request.method == "POST":
        form = CursoForm(request.POST, instance=obj)
        if form.is_valid():
            obj = form.save()
            messages.add_message(request, messages.INFO, 'Curso actualizado correctamente')
            return redirect("cursos:detail", id=obj.id)
    else:
        form = CursoForm(instance=obj)

    return render(request, "cursos/nuevo.html", {"form": form, "title":"Editar curso"})


def curso_borrar(request, id):
    obj = get_object_or_404(Curso, id=id)

    if request.method == "POST":
        try:
            obj.delete()
        except:
            messages.add_message(request, messages.ERROR, 'Ha ocurrido un error inesperado al borrar')
            return redirect("cursos:list")
        messages.add_message(request, messages.INFO, 'Curso borrado correctamente')
        return redirect("cursos:list")

    return render(request, "cursos/borrar.html", {"curso": obj})


def curso_nuevo_alumno(request, id):
    curso = get_object_or_404(Curso, id=id)

    if request.method == "POST":
        form = AlumnoForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.curso = curso
            obj.save()
            messages.add_message(request, messages.INFO, 'Alumno creado correctamente')
            return redirect("cursos:detail", id=curso.id)
    else:
        form = AlumnoForm()

    return render(request, "cursos/nuevo_alumno.html", {"form": form,  "title":"Nuevo alumno"})


def curso_editar_alumno(request, id, alumno_id):
    pass

def curso_borrar_alumno(request, id, alumno_id):
    pass

minerva/cursos/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Minerva</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <style>
        .errorlist li {color:red;}
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url "home" %}">Minerva</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "home" %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "cursos:list" %}">Cursos</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="mt-3">

      <div class="jumbotron">
        <h1>{% block title %}{% endblock %}</h1>
        <p class="lead">{% block subtitle %}{% endblock subtitle %}</p>
      </div>

        {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}

      <div class="container">        
        {% block main %}
        {% endblock main %}
      </div>

    </main><!-- /.container -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>

    {% block scripts %}
        
    {% endblock scripts %}
  </body>
</html>

minerva/cursos/templates/cursos/borrar.html
{% extends "base.html" %}

{% block title %}{{curso.nombre}}{% endblock %}
{% block subtitle %}Borrar curso{% endblock subtitle %}

{% block main %}

  <div class="alert alert-danger">
    <h3><span class="oi oi-trash"></span> Atención</h3>
    <p>¿Estás seguro de que deseas borrar?</p>

    <form action="." method="POST" class="float-right">
      {% csrf_token %}
      <button class="btn btn-danger" type="submit"><span class="oi oi-trash"></span> Borrar</button>
    </form>      
    <a href="{% url "cursos:list" %}" class="btn btn-secondary"><span class="oi oi-chevron-left"></span> Cancelar y volver</a>
  </div>
  
{% endblock main %}

minerva/cursos/templates/cursos/detail.html
{% extends "base.html" %}

{% block title %}{{curso.nombre}}{% endblock %}
{% block subtitle %}Ficha del curso{% endblock subtitle %}

{% block main %}

  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <table class="table">
          <tbody>
            <tr>
              <th>Nombre</th>
              <td>{{curso.nombre}}</td>
            </tr>
            <tr>
              <th>Fecha de inicio</th>
              <td>{{curso.fecha_inicio}}</td>
            </tr>
            <tr>
              <th>Fecha de fin</th>
              <td>{{curso.fecha_fin}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <table class="table">
          <tbody>
            <tr>
              <th>Horario</th>
              <td>{{curso.get_horario_display}}</td>
            </tr>
            <tr>
              <th>Modalidad</th>
              <td>{{curso.modalidad.nombre}}</td>
            </tr>
            <tr>
              <th>Plazas</th>
              <td>{{curso.plazas}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <a href="{% url "cursos:nuevo_alumno" curso.id %}" class="float-right btn btn-success"><span class="oi oi-plus"></span> Nuevo alumno</a>          
          <h3>Listado de alumnos matriculados</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellidos</th>
              <th>Fecha de matrícula</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for alumno in curso.alumnomatriculado_set.all %}
            <tr>
              <td>{{alumno.nombre}}</td>
              <td>{{alumno.apellidos}}</td>
              <td>{{alumno.fecha_matricula|date:"d/m/Y"}}</td>
              <td>
                  <a href="{% url "cursos:editar_alumno" curso.id alumno.id %}" class="btn text-warning"><span class="oi oi-pencil"></span></a> 
                  <a href="{% url "cursos:borrar_alumno" curso.id alumno.id %}" class="btn text-danger"><span class="oi oi-trash"></span></a> 
              </td>
            </tr>{% endfor %}
          </tbody>
        </table>
      </div>      
    </div>
  </div>

{% endblock main %}

minerva/cursos/templates/cursos/home.html
{% extends "base.html" %}

{% block title %}Minerva{% endblock %}
{% block subtitle %}Que mina hierbas{% endblock subtitle %}

{% block main %}
    
          <div class="row">
              <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5>Próximos cursos</h5>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Fecha de inicio</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for curso in proximos %}
                            <tr>
                                <td>{{curso.nombre}}</td>
                                <td>{{curso.fecha_inicio|date:"d/m/Y"}}</td>
                            </tr>{% endfor %}
                        </tbody>
                    </table>
                    <div class="card-footer">
                        <a href="{% url "cursos:list" %}" class="btn btn-primary">Ver todos los cursos</a>
                    </div>
                </div>
              </div>
              <div class="col-md-6">
                  
              </div>
          </div>
          
{% endblock main %}

minerva/cursos/templates/cursos/list.html
{% extends "base.html" %}

{% block title %}Cursos{% endblock %}
{% block subtitle %}Listado de cursos{% endblock subtitle %}

{% block main %}

  <div class="row">
    <div class="col-md-12">

        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="./" class="btn btn-secondary">Todos</a>
          {% for modalidad in modalidades %}
          <a href="?modalidad={{modalidad.id}}" class="btn btn-secondary">{{modalidad.nombre}}</a>
          {% endfor %}
        </div>        
      <div class="card mt-3">
        <div class="card-header">
          <a href="{% url "cursos:nuevo" %}" class="float-right btn btn-success"><span class="oi oi-plus"></span> Nuevo curso</a>
          <h2>Listado de cursos</h2>
          <p>Hay {{cursos.count}} curso{{cursos.count|pluralize}}</p>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Fecha inicio</th>
              <th>Fecha fin</th>
              <th>Plazas</th>
              <th>Plazas (Porc)</th>
              <th>Modalidad</th>
              <th>Subvencionado</th>
              <th>Horas</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {% for curso in cursos %}
            <tr>
              <td>{{curso.nombre}}</td>
              <td>{{curso.fecha_inicio|date:"d/m/Y"}}</td>
              <td>{{curso.fecha_fin|date:"d/m/Y"}}</td>
              <td>{{curso.porcentaje_plazas}}% ({{curso.plazas}})</td>
              <td>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="{{curso.porcentaje_plazas}}" style="width: {{curso.porcentaje_plazas}}%" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </td>
              <td>{{curso.modalidad.nombre}}</td>
              <td align="center"><span class="text-{{curso.subvencionado|yesno:"success,danger"}} oi oi-{{curso.subvencionado|yesno:"check,x"}}"></span></td>
              <td>{{curso.horas}}</td>
              <td>
                <div class="btn-group">
                  <a href="{% url "cursos:detail" curso.id %}" class="btn text-primary"><span class="oi oi-eye"></span></a> 
                  <a href="{% url "cursos:editar" curso.id %}" class="btn text-warning"><span class="oi oi-pencil"></span></a> 
                  <a href="{% url "cursos:borrar" curso.id %}" class="btn text-danger"><span class="oi oi-trash"></span></a> 
                </div>
              </td>
            </tr>{% endfor %}
          </tbody>
        </table>
        <div class="card-footer"></div>
      </div>
    </div>
  </div>

{% endblock main %}

minerva/cursos/templates/cursos/nuevo.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Cursos{% endblock %}
{% block subtitle %}{{title}}{% endblock subtitle %}

{% block main %}

  <div class="row">
    <div class="col-md-12">
      <form action="." method="POST">      
        {% csrf_token %}
        <div class="card">
          <div class="card-header">
            <h5>{{title}}</h5>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  {{form.nombre.label_tag}}
                  {{form.nombre|add_class:"form-control"}}
                  {{form.nombre.errors}}
                </div>
              </div>            
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  {{form.fecha_inicio.label_tag}}
                  {{form.fecha_inicio|add_class:"form-control"}}
                  {{form.fecha_inicio.errors}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  {{form.fecha_fin.label_tag}}
                  {{form.fecha_fin|add_class:"form-control"}}
                  {{form.fecha_fin.errors}}
                </div>
              </div>              
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  {{form.modalidad.label_tag}}
                  {{form.modalidad|add_class:"form-control"}}
                  {{form.modalidad.errors}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  {{form.horas.label_tag}}
                  {{form.horas|add_class:"form-control"}}
                  {{form.horas.errors}}
                </div>
              </div>              
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  {{form.plazas.label_tag}}
                  {{form.plazas|add_class:"form-control"}}
                  {{form.plazas.errors}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  {{form.horario.label_tag}}
                  {{form.horario|add_class:"form-control"}}
                  {{form.horario.errors}}
                </div>
              </div>              
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-check">
                  {{form.subvencionado}}
                  <label class="form-check-label" for="{{form.subvencionado.id_for_label}}">Subvencionado</label>
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>
        </div>
      </form>
    </div>
  </div>


{% endblock main %}

{% block scripts %}

{% endblock scripts %}